### ISSUE TITLE
Bugas ar dar vienas "Easter Egg"?

### ISSUE THREAD

**Issue by lukjok** [MELPDRLZ/True-KTU-android-app#12]
Viską pasako screenshot 
![screenshot_20180506-185022](https://user-images.githubusercontent.com/28230845/39675091-be8091c2-515e-11e8-8be3-5736fac0a4f8.jpg)

**Comment by EimantasN** [comment]
Ačiū, kad pranešėi. Sutvarkysiu artimiausiu metu.
